# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/CollegeStuff/Final_Year_project/XtalOpt-14.3.0_SourceCode/XtalOpt-14.3.0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/CollegeStuff/Final_Year_project/XtalOpt-14.3.0_SourceCode/XtalOpt-14.3.0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /mnt/d/CollegeStuff/Final_Year_project/XtalOpt-14.3.0_SourceCode/XtalOpt-14.3.0/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/CollegeStuff/Final_Year_project/XtalOpt-14.3.0_SourceCode/XtalOpt-14.3.0/CMakeFiles /mnt/d/CollegeStuff/Final_Year_project/XtalOpt-14.3.0_SourceCode/XtalOpt-14.3.0//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/CollegeStuff/Final_Year_project/XtalOpt-14.3.0_SourceCode/XtalOpt-14.3.0/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pugixml

# Build rule for target.
pugixml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pugixml
.PHONY : pugixml

# fast build rule for target.
pugixml/fast:
	$(MAKE) $(MAKESILENT) -f external/pugixml/CMakeFiles/pugixml.dir/build.make external/pugixml/CMakeFiles/pugixml.dir/build
.PHONY : pugixml/fast

#=============================================================================
# Target rules for targets named pugixml_autogen_timestamp_deps

# Build rule for target.
pugixml_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pugixml_autogen_timestamp_deps
.PHONY : pugixml_autogen_timestamp_deps

# fast build rule for target.
pugixml_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f external/pugixml/CMakeFiles/pugixml_autogen_timestamp_deps.dir/build.make external/pugixml/CMakeFiles/pugixml_autogen_timestamp_deps.dir/build
.PHONY : pugixml_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named pugixml_autogen

# Build rule for target.
pugixml_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pugixml_autogen
.PHONY : pugixml_autogen

# fast build rule for target.
pugixml_autogen/fast:
	$(MAKE) $(MAKESILENT) -f external/pugixml/CMakeFiles/pugixml_autogen.dir/build.make external/pugixml/CMakeFiles/pugixml_autogen.dir/build
.PHONY : pugixml_autogen/fast

#=============================================================================
# Target rules for targets named RandSpg

# Build rule for target.
RandSpg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RandSpg
.PHONY : RandSpg

# fast build rule for target.
RandSpg/fast:
	$(MAKE) $(MAKESILENT) -f external/randSpg/CMakeFiles/RandSpg.dir/build.make external/randSpg/CMakeFiles/RandSpg.dir/build
.PHONY : RandSpg/fast

#=============================================================================
# Target rules for targets named RandSpg_autogen_timestamp_deps

# Build rule for target.
RandSpg_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RandSpg_autogen_timestamp_deps
.PHONY : RandSpg_autogen_timestamp_deps

# fast build rule for target.
RandSpg_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f external/randSpg/CMakeFiles/RandSpg_autogen_timestamp_deps.dir/build.make external/randSpg/CMakeFiles/RandSpg_autogen_timestamp_deps.dir/build
.PHONY : RandSpg_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named RandSpg_autogen

# Build rule for target.
RandSpg_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RandSpg_autogen
.PHONY : RandSpg_autogen

# fast build rule for target.
RandSpg_autogen/fast:
	$(MAKE) $(MAKESILENT) -f external/randSpg/CMakeFiles/RandSpg_autogen.dir/build.make external/randSpg/CMakeFiles/RandSpg_autogen.dir/build
.PHONY : RandSpg_autogen/fast

#=============================================================================
# Target rules for targets named spglib

# Build rule for target.
spglib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spglib
.PHONY : spglib

# fast build rule for target.
spglib/fast:
	$(MAKE) $(MAKESILENT) -f external/spglib/CMakeFiles/spglib.dir/build.make external/spglib/CMakeFiles/spglib.dir/build
.PHONY : spglib/fast

#=============================================================================
# Target rules for targets named spglib_autogen_timestamp_deps

# Build rule for target.
spglib_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spglib_autogen_timestamp_deps
.PHONY : spglib_autogen_timestamp_deps

# fast build rule for target.
spglib_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f external/spglib/CMakeFiles/spglib_autogen_timestamp_deps.dir/build.make external/spglib/CMakeFiles/spglib_autogen_timestamp_deps.dir/build
.PHONY : spglib_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named spglib_autogen

# Build rule for target.
spglib_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spglib_autogen
.PHONY : spglib_autogen

# fast build rule for target.
spglib_autogen/fast:
	$(MAKE) $(MAKESILENT) -f external/spglib/CMakeFiles/spglib_autogen.dir/build.make external/spglib/CMakeFiles/spglib_autogen.dir/build
.PHONY : spglib_autogen/fast

#=============================================================================
# Target rules for targets named XtalComp

# Build rule for target.
XtalComp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XtalComp
.PHONY : XtalComp

# fast build rule for target.
XtalComp/fast:
	$(MAKE) $(MAKESILENT) -f external/xtalcomp/CMakeFiles/XtalComp.dir/build.make external/xtalcomp/CMakeFiles/XtalComp.dir/build
.PHONY : XtalComp/fast

#=============================================================================
# Target rules for targets named XtalComp_autogen_timestamp_deps

# Build rule for target.
XtalComp_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XtalComp_autogen_timestamp_deps
.PHONY : XtalComp_autogen_timestamp_deps

# fast build rule for target.
XtalComp_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f external/xtalcomp/CMakeFiles/XtalComp_autogen_timestamp_deps.dir/build.make external/xtalcomp/CMakeFiles/XtalComp_autogen_timestamp_deps.dir/build
.PHONY : XtalComp_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named XtalComp_autogen

# Build rule for target.
XtalComp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XtalComp_autogen
.PHONY : XtalComp_autogen

# fast build rule for target.
XtalComp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f external/xtalcomp/CMakeFiles/XtalComp_autogen.dir/build.make external/xtalcomp/CMakeFiles/XtalComp_autogen.dir/build
.PHONY : XtalComp_autogen/fast

#=============================================================================
# Target rules for targets named qhullstatic_r

# Build rule for target.
qhullstatic_r: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qhullstatic_r
.PHONY : qhullstatic_r

# fast build rule for target.
qhullstatic_r/fast:
	$(MAKE) $(MAKESILENT) -f external/qhull/CMakeFiles/qhullstatic_r.dir/build.make external/qhull/CMakeFiles/qhullstatic_r.dir/build
.PHONY : qhullstatic_r/fast

#=============================================================================
# Target rules for targets named qhullcpp

# Build rule for target.
qhullcpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qhullcpp
.PHONY : qhullcpp

# fast build rule for target.
qhullcpp/fast:
	$(MAKE) $(MAKESILENT) -f external/qhull/CMakeFiles/qhullcpp.dir/build.make external/qhull/CMakeFiles/qhullcpp.dir/build
.PHONY : qhullcpp/fast

#=============================================================================
# Target rules for targets named qhullstatic_r_autogen_timestamp_deps

# Build rule for target.
qhullstatic_r_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qhullstatic_r_autogen_timestamp_deps
.PHONY : qhullstatic_r_autogen_timestamp_deps

# fast build rule for target.
qhullstatic_r_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f external/qhull/CMakeFiles/qhullstatic_r_autogen_timestamp_deps.dir/build.make external/qhull/CMakeFiles/qhullstatic_r_autogen_timestamp_deps.dir/build
.PHONY : qhullstatic_r_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named qhullstatic_r_autogen

# Build rule for target.
qhullstatic_r_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qhullstatic_r_autogen
.PHONY : qhullstatic_r_autogen

# fast build rule for target.
qhullstatic_r_autogen/fast:
	$(MAKE) $(MAKESILENT) -f external/qhull/CMakeFiles/qhullstatic_r_autogen.dir/build.make external/qhull/CMakeFiles/qhullstatic_r_autogen.dir/build
.PHONY : qhullstatic_r_autogen/fast

#=============================================================================
# Target rules for targets named qhullcpp_autogen_timestamp_deps

# Build rule for target.
qhullcpp_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qhullcpp_autogen_timestamp_deps
.PHONY : qhullcpp_autogen_timestamp_deps

# fast build rule for target.
qhullcpp_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f external/qhull/CMakeFiles/qhullcpp_autogen_timestamp_deps.dir/build.make external/qhull/CMakeFiles/qhullcpp_autogen_timestamp_deps.dir/build
.PHONY : qhullcpp_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named qhullcpp_autogen

# Build rule for target.
qhullcpp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qhullcpp_autogen
.PHONY : qhullcpp_autogen

# fast build rule for target.
qhullcpp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f external/qhull/CMakeFiles/qhullcpp_autogen.dir/build.make external/qhull/CMakeFiles/qhullcpp_autogen.dir/build
.PHONY : qhullcpp_autogen/fast

#=============================================================================
# Target rules for targets named globalsearch

# Build rule for target.
globalsearch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 globalsearch
.PHONY : globalsearch

# fast build rule for target.
globalsearch/fast:
	$(MAKE) $(MAKESILENT) -f src/globalsearch/CMakeFiles/globalsearch.dir/build.make src/globalsearch/CMakeFiles/globalsearch.dir/build
.PHONY : globalsearch/fast

#=============================================================================
# Target rules for targets named globalsearch_autogen_timestamp_deps

# Build rule for target.
globalsearch_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 globalsearch_autogen_timestamp_deps
.PHONY : globalsearch_autogen_timestamp_deps

# fast build rule for target.
globalsearch_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/globalsearch/CMakeFiles/globalsearch_autogen_timestamp_deps.dir/build.make src/globalsearch/CMakeFiles/globalsearch_autogen_timestamp_deps.dir/build
.PHONY : globalsearch_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named globalsearch_autogen

# Build rule for target.
globalsearch_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 globalsearch_autogen
.PHONY : globalsearch_autogen

# fast build rule for target.
globalsearch_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/globalsearch/CMakeFiles/globalsearch_autogen.dir/build.make src/globalsearch/CMakeFiles/globalsearch_autogen.dir/build
.PHONY : globalsearch_autogen/fast

#=============================================================================
# Target rules for targets named xtalopt_static

# Build rule for target.
xtalopt_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xtalopt_static
.PHONY : xtalopt_static

# fast build rule for target.
xtalopt_static/fast:
	$(MAKE) $(MAKESILENT) -f src/xtalopt/CMakeFiles/xtalopt_static.dir/build.make src/xtalopt/CMakeFiles/xtalopt_static.dir/build
.PHONY : xtalopt_static/fast

#=============================================================================
# Target rules for targets named xtalopt

# Build rule for target.
xtalopt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xtalopt
.PHONY : xtalopt

# fast build rule for target.
xtalopt/fast:
	$(MAKE) $(MAKESILENT) -f src/xtalopt/CMakeFiles/xtalopt.dir/build.make src/xtalopt/CMakeFiles/xtalopt.dir/build
.PHONY : xtalopt/fast

#=============================================================================
# Target rules for targets named xtalopt_static_autogen_timestamp_deps

# Build rule for target.
xtalopt_static_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xtalopt_static_autogen_timestamp_deps
.PHONY : xtalopt_static_autogen_timestamp_deps

# fast build rule for target.
xtalopt_static_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/xtalopt/CMakeFiles/xtalopt_static_autogen_timestamp_deps.dir/build.make src/xtalopt/CMakeFiles/xtalopt_static_autogen_timestamp_deps.dir/build
.PHONY : xtalopt_static_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named xtalopt_static_autogen

# Build rule for target.
xtalopt_static_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xtalopt_static_autogen
.PHONY : xtalopt_static_autogen

# fast build rule for target.
xtalopt_static_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/xtalopt/CMakeFiles/xtalopt_static_autogen.dir/build.make src/xtalopt/CMakeFiles/xtalopt_static_autogen.dir/build
.PHONY : xtalopt_static_autogen/fast

#=============================================================================
# Target rules for targets named xtalopt_autogen_timestamp_deps

# Build rule for target.
xtalopt_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xtalopt_autogen_timestamp_deps
.PHONY : xtalopt_autogen_timestamp_deps

# fast build rule for target.
xtalopt_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/xtalopt/CMakeFiles/xtalopt_autogen_timestamp_deps.dir/build.make src/xtalopt/CMakeFiles/xtalopt_autogen_timestamp_deps.dir/build
.PHONY : xtalopt_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named xtalopt_autogen

# Build rule for target.
xtalopt_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xtalopt_autogen
.PHONY : xtalopt_autogen

# fast build rule for target.
xtalopt_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/xtalopt/CMakeFiles/xtalopt_autogen.dir/build.make src/xtalopt/CMakeFiles/xtalopt_autogen.dir/build
.PHONY : xtalopt_autogen/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... RandSpg_autogen"
	@echo "... RandSpg_autogen_timestamp_deps"
	@echo "... XtalComp_autogen"
	@echo "... XtalComp_autogen_timestamp_deps"
	@echo "... globalsearch_autogen"
	@echo "... globalsearch_autogen_timestamp_deps"
	@echo "... pugixml_autogen"
	@echo "... pugixml_autogen_timestamp_deps"
	@echo "... qhullcpp_autogen"
	@echo "... qhullcpp_autogen_timestamp_deps"
	@echo "... qhullstatic_r_autogen"
	@echo "... qhullstatic_r_autogen_timestamp_deps"
	@echo "... spglib_autogen"
	@echo "... spglib_autogen_timestamp_deps"
	@echo "... xtalopt_autogen"
	@echo "... xtalopt_autogen_timestamp_deps"
	@echo "... xtalopt_static_autogen"
	@echo "... xtalopt_static_autogen_timestamp_deps"
	@echo "... RandSpg"
	@echo "... XtalComp"
	@echo "... globalsearch"
	@echo "... pugixml"
	@echo "... qhullcpp"
	@echo "... qhullstatic_r"
	@echo "... spglib"
	@echo "... xtalopt"
	@echo "... xtalopt_static"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

